lib: [
  "_build/install/default/lib/qinap/META"
  "_build/install/default/lib/qinap/dune-package"
  "_build/install/default/lib/qinap/opam"
  "_build/install/default/lib/qinap/qinap.a"
  "_build/install/default/lib/qinap/qinap.cma"
  "_build/install/default/lib/qinap/qinap.cmi"
  "_build/install/default/lib/qinap/qinap.cmt"
  "_build/install/default/lib/qinap/qinap.cmti"
  "_build/install/default/lib/qinap/qinap.cmx"
  "_build/install/default/lib/qinap/qinap.cmxa"
  "_build/install/default/lib/qinap/qinap.cmxs"
  "_build/install/default/lib/qinap/qinap.ml"
  "_build/install/default/lib/qinap/qinap.mli"
]
doc: [
  "_build/install/default/doc/qinap/README.md"
]
